<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Whoops' => array($vendorDir . '/filp/whoops/src'),
    'PhpConsole' => array($vendorDir . '/php-console/php-console/src'),
);
