<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Inspekt\\' => array($vendorDir . '/funkatron/inspekt/src/Inspekt'),
);
